# Copyright © 2025, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""AML Tier 10 tools: SAS Visual Investigator Alerts API (read-only)."""

from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import Any

import httpx
from fastmcp import Context, FastMCP

from ..config import VIYA_ENDPOINT
from ..viya_client import get_json, logger, make_client


def register_aml_alerts(mcp: FastMCP, get_token) -> None:
    @asynccontextmanager
    async def viya_session(name: str, ctx: Context) -> AsyncIterator[httpx.AsyncClient]:
        logger.info("--- TOOL USED: %s ---", name)
        token = await get_token(ctx)
        async with make_client(token) as client:
            yield client

    # ------------------------------------------------------------------
    # Tier 10 — SAS AML / Visual Investigator (READ-ONLY alerts)
    # ------------------------------------------------------------------
    # Wrap the SAS Visual Investigator Alerts REST API (/svi-alert). These
    # expose the productised alert objects — scores, status, the actionable
    # entity an alert is about, and WHY it fired (scenario-fired events) — so
    # the agent reads validated product data instead of re-deriving detection
    # from raw CAS transaction tables. Deliberately READ-ONLY: alert
    # disposition / assignment / workflow writes are NOT exposed (governance:
    # the agent produces analyst-reviewable findings, not confirmed actions).

    _SVI_ALERT = "/svi-alert/alerts"

    def _alert_summary(a: dict[str, Any]) -> dict[str, Any]:
        """Pick the fields an AML analyst needs from a VI alert object."""
        return {
            "alertId": a.get("alertId"),
            "alertTypeCode": a.get("alertTypeCode"),
            "alertStatusId": a.get("alertStatusId"),
            "currentScore": a.get("currentScore"),
            "highScore": a.get("highScore"),
            "initialScore": a.get("initialScore"),
            "entityId": a.get("actionableEntityId"),
            "entityType": a.get("actionableEntityType"),
            "entityLabel": a.get("actionableEntityLabel"),
            "queueId": a.get("queueId"),
            "domainId": a.get("domainId"),
            "creationTimeStamp": a.get("creationTimeStamp"),
            "statusTimeStamp": a.get("statusTimeStamp"),
        }

    def _sfe_summary(e: dict[str, Any]) -> dict[str, Any]:
        """Pick the auditable 'why it fired' fields from a scenario-fired event."""
        return {
            "scenarioFiredEventId": e.get("scenarioFiredEventId"),
            "scenarioId": e.get("scenarioId"),
            "scenarioName": e.get("scenarioName"),
            "scenarioDescription": e.get("scenarioDescription"),
            "ruleId": e.get("ruleId"),
            "score": e.get("score"),
            "appliedSegmentCode": e.get("appliedSegmentCode"),
            "alertingEventId": e.get("alertingEventId"),
            "firedEntityId": e.get("scenarioFiredEntityId"),
            "firedEntityType": e.get("scenarioFiredEntityType"),
            "message": e.get("messageTemplateText"),
            "contextStartTimeStamp": e.get("contextStartTimeStamp"),
            "contextEndTimeStamp": e.get("contextEndTimeStamp"),
            "creationTimeStamp": e.get("creationTimeStamp"),
        }

    @mcp.tool()
    async def list_alerts(ctx: Context, limit: int = 20, start: int = 0,
                          filter_expr: str | None = None,
                          sort_by: str | None = None) -> dict[str, Any]:
        """List SAS Visual Investigator (AML) alerts — already-detected, scored alerts.

        PREFER THIS over aggregating raw CAS transaction tables: these alerts
        were generated by the scenario engine and carry scores, status, and the
        entity each alert is about. Read-only.

        Args:
            limit: Max alerts to return (default 20).
            start: Pagination offset (default 0).
            filter_expr: Optional SAS filter expression, e.g.
                ``eq(alertStatusId,'NEW')`` or ``gt(currentScore,80)``.
            sort_by: Optional sort, e.g. ``currentScore:descending``.

        Returns:
            ``{"count": <total>, "start": <offset>, "alerts": [ {summary} ]}``.
            Each summary has alertId, scores, status, and the actionable entity
            (entityId / entityType / entityLabel) the alert concerns.
        """
        params: dict[str, Any] = {"start": start, "limit": limit}
        if filter_expr:
            params["filter"] = filter_expr
        if sort_by:
            params["sortBy"] = sort_by
        async with viya_session("list_alerts", ctx) as client:
            data = await get_json(_SVI_ALERT, client, params=params)
        items = data.get("items", [])
        return {
            "count": data.get("count", len(items)),
            "start": data.get("start", start),
            "alerts": [_alert_summary(a) for a in items],
        }

    @mcp.tool()
    async def get_alert(alert_id: str, ctx: Context) -> dict[str, Any]:
        """Get one VI/AML alert by id — full object (scores, status, entity, timestamps).

        Args:
            alert_id: The alertId (from ``list_alerts``).
        """
        async with viya_session("get_alert", ctx) as client:
            return await get_json(f"{_SVI_ALERT}/{alert_id}", client)

    @mcp.tool()
    async def get_alert_scorecard(alert_id: str, ctx: Context) -> dict[str, Any]:
        """Get the score breakdown (scorecard) for a VI/AML alert — why it scored as it did.

        Args:
            alert_id: The alertId.
        """
        async with viya_session("get_alert_scorecard", ctx) as client:
            return await get_json(f"{_SVI_ALERT}/{alert_id}/scorecard", client)

    # This collection requires an Accept-Item header naming the item media type
    # (confirmed against the svi-alert OpenAPI spec). Without it the endpoint
    # returns 400 ("Required header 'Accept-Item' is not present").
    _SFE_ITEM_TYPE = (
        "application/vnd.sas.investigation.triage.scenario.fired.event.extended+json"
    )

    @mcp.tool()
    async def get_scenario_fired_events(alert_id: str, ctx: Context,
                                        limit: int = 50, start: int = 0) -> dict[str, Any]:
        """Get scenario-fired events for a VI/AML alert — which detection scenarios triggered it.

        This is the auditable "why" behind an alert: the scenario(s) that fired,
        their description, rule, score, and the fired entity. Use this instead of
        guessing a typology from raw transactions.

        Args:
            alert_id: The alertId.
            limit: Max events to return (default 50).
            start: Pagination offset (default 0).

        Returns:
            ``{"count": <total>, "events": [ {scenarioName, scenarioDescription,
            ruleId, score, message, firedEntityId/Type, timestamps} ]}``.
        """
        url = f"{VIYA_ENDPOINT}{_SVI_ALERT}/{alert_id}/scenarioFiredEvents"
        async with viya_session("get_scenario_fired_events", ctx) as client:
            resp = await client.get(
                url,
                headers={"Accept": "application/vnd.sas.collection+json",
                         "Accept-Item": _SFE_ITEM_TYPE},
                params={"start": start, "limit": limit},
            )
            resp.raise_for_status()
            data = resp.json()
        items = data.get("items", [])
        return {"count": data.get("count", len(items)),
                "events": [_sfe_summary(e) for e in items]}
